export default {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'Best Slim Shirt in the whole world',
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 70,
      brand: 'Wrogn',
      rating: 4.5,
      numReview: 10,
      description: ' Perfect fit for you',
    },
    {
      _id: '3',
      name: 'Fit Pant',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 65,
      brand: 'Adidas',
      rating: 4.5,
      numReview: 10,
    },
  ],
};
